-- =====================================================
-- Stage 0: Product Intelligence Foundation
-- Migration 023: Populate Complete Sauce Knowledge Base
-- =====================================================

-- Insert all 15 sauces with complete flavor profiles
INSERT INTO products.sauces (
  sauce_name, display_name, short_name, primary_flavor, secondary_flavor,
  spice_level, spice_type, sweetness, savory, tanginess, smokiness, heat,
  texture, base_ingredients, description, customer_descriptors, tags,
  is_dip, is_wing_sauce
) VALUES
(
  'island_bbq',
  'Island BBQ (Authentic Chipotle BBQ Chilli Glaze)',
  'Island BBQ',
  'smoky',
  'sweet',
  3,
  'mild_heat',
  6, 7, 3, 6, 3,
  'sticky / thick',
  ARRAY['tomato paste', 'brown sugar', 'chipotle pepper'],
  'Smoky-sweet glaze with chipotle warmth – rich BBQ heat with a twist.',
  ARRAY['the chipotle one', 'smoky BBQ', 'island'],
  ARRAY['smoky', 'sweet', 'mild', 'sticky', 'BBQ'],
  true,
  true
),
(
  'smokey_bbq',
  'Smokey BBQ',
  'Smokey BBQ',
  'smoky',
  'sweet',
  1,
  'none',
  7, 6, 2, 7, 1,
  'thick / glossy',
  ARRAY['molasses', 'tomato', 'paprika'],
  'Smooth classic BBQ, gentle smoke, minimal burn.',
  ARRAY['classic BBQ', 'regular BBQ'],
  ARRAY['smoky', 'sweet', 'mild'],
  true,
  true
),
(
  'changs_honey_sesame',
  'Chang''s Honey Sesame',
  'Honey Sesame',
  'sweet',
  'savoury',
  1,
  'none',
  9, 4, 2, 1, 1,
  'sticky',
  ARRAY['honey', 'sesame oil', 'soy sauce'],
  'Sticky, nutty, delicate – customers call it "the sweet one."',
  ARRAY['honey sesame', 'the sweet one', 'HS', 'sesame'],
  ARRAY['sweet', 'sticky', 'mild', 'popular'],
  true,
  true
),
(
  'korean_heat',
  'Korean Heat (BBQ Sauce)',
  'Korean Heat',
  'spicy',
  'sweet',
  7,
  'hot',
  5, 7, 3, 2, 7,
  'thick',
  ARRAY['gochujang', 'soy', 'garlic', 'chilli'],
  'Deep umami with fermented-chilli kick – "sweet heat with depth."',
  ARRAY['korean', 'gochujang', 'KH'],
  ARRAY['spicy', 'umami', 'hot', 'Korean'],
  true,
  true
),
(
  'flamin_hoisin',
  'Flamin Hoisin',
  'Flamin Hoisin',
  'tangy',
  'spicy',
  5,
  'medium_heat',
  6, 6, 7, 1, 5,
  'sticky / vinegary',
  ARRAY['hoisin', 'vinegar', 'chilli', 'garlic'],
  'Tangy-sweet Asian heat with a fruity finish – balanced medium spice.',
  ARRAY['hoisin', 'flaming hoisin'],
  ARRAY['tangy', 'sweet', 'medium', 'sticky'],
  true,
  true
),
(
  'jarvs_tangy_buffalo',
  'Jarv''s Tangy Buffalo (Buffalo Sauce)',
  'Jarv''s Buffalo',
  'tangy',
  'spicy',
  5,
  'medium_heat',
  2, 5, 8, 0, 5,
  'vinegary / runny',
  ARRAY['vinegar', 'cayenne pepper', 'butter'],
  'True Buffalo punch – sharp, buttery, mouth-tingling.',
  ARRAY['buffalo', 'Jarv''s', 'jarvs', 'tang buff', 'the tangy one'],
  ARRAY['tangy', 'spicy', 'buffalo', 'medium'],
  true,
  true
),
(
  'honey_mustard',
  'Honey Mustard',
  'Honey Mustard',
  'sweet',
  'tangy',
  2,
  'mild_heat',
  8, 5, 4, 0, 2,
  'creamy',
  ARRAY['honey', 'mustard', 'vinegar'],
  'Sweet and zesty – perfect for non-spice fans.',
  ARRAY['honey must', 'HM'],
  ARRAY['sweet', 'tangy', 'mild', 'creamy'],
  true,
  true
),
(
  'mango_mazzaline',
  '🔥 Mango Mazzaline (Scotch Bonnet Mango Sauce)',
  'Mango Mazzaline',
  'spicy',
  'fruity',
  9,
  'very_hot',
  7, 3, 3, 0, 9,
  'syrupy',
  ARRAY['mango purée', 'scotch bonnet', 'vinegar', 'sugar'],
  'Tropical mango heat powered by Scotch Bonnets – fruity sweetness with serious burn.',
  ARRAY['mango', 'mazzaline', 'scotch bonnet', 'the mango one', 'tropical heat'],
  ARRAY['spicy', 'very_hot', 'fruity', 'tropical'],
  true,
  true
),
(
  'sweet_chilli',
  'Sweet Chilli',
  'Sweet Chilli',
  'sweet',
  'spicy',
  2,
  'mild_heat',
  9, 3, 3, 0, 2,
  'sticky',
  ARRAY['red chilli', 'sugar', 'vinegar'],
  'Familiar Asian-style sweet-heat.',
  ARRAY['sweet chili', 'SC'],
  ARRAY['sweet', 'mild', 'sticky'],
  true,
  true
),
(
  'plain',
  'Plain',
  'Plain',
  'savoury',
  NULL,
  0,
  'none',
  0, 4, 0, 0, 0,
  'n/a',
  ARRAY['chicken base only'],
  'Naked wing – no sauce.',
  ARRAY['no sauce', 'dry', 'plain wings'],
  ARRAY['plain', 'unsauced'],
  false,
  true
),
(
  'sriracha_mayo',
  'Sriracha Mayo (Shack Sauce)',
  'Shack Sauce',
  'spicy',
  'creamy',
  2,
  'mild_heat',
  3, 6, 4, 0, 2,
  'creamy',
  ARRAY['sriracha (8%)', 'egg mayo (92%)', 'mustard'],
  'Creamy chilli mayo – gentle warmth, crowd-friendly.',
  ARRAY['shack sauce', 'sriracha', 'spicy mayo'],
  ARRAY['creamy', 'mild', 'spicy', 'popular'],
  true,
  false
),
(
  'blue_cheese',
  'Blue Cheese',
  'Blue Cheese',
  'savoury',
  'tangy',
  0,
  'none',
  2, 8, 5, 0, 0,
  'creamy',
  ARRAY['blue cheese', 'cream'],
  'Rich and cooling dip that balances Buffalo heat.',
  ARRAY['bleu cheese', 'blue'],
  ARRAY['savory', 'cooling', 'dip'],
  true,
  false
),
(
  'ketchup',
  'Ketchup',
  'Ketchup',
  'sweet',
  'tangy',
  0,
  'none',
  7, 2, 3, 0, 0,
  'smooth',
  ARRAY['tomato', 'vinegar', 'sugar'],
  'Classic tomato ketchup dip.',
  ARRAY['tomato sauce'],
  ARRAY['sweet', 'classic', 'dip'],
  true,
  false
),
(
  'mayo',
  'Mayo',
  'Mayo',
  'savoury',
  'creamy',
  0,
  'none',
  1, 3, 1, 0, 0,
  'creamy',
  ARRAY['egg', 'oil', 'vinegar'],
  'Classic mayonnaise dip.',
  ARRAY['mayonnaise', 'mayonaise'],
  ARRAY['creamy', 'classic', 'dip'],
  true,
  false
);

-- Verify sauce population
SELECT 
  sauce_name,
  display_name,
  primary_flavor,
  spice_level,
  sweetness,
  is_wing_sauce,
  is_dip
FROM products.sauces 
ORDER BY spice_level, primary_flavor;

-- Count verification
SELECT COUNT(*) as total_sauces FROM products.sauces;
-- Expected: 15 sauces
